name: Node CI (Jest & Generate Test)
# env:
#   TZ: Asia/Tokyo

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Jest Test
      run: |
        yarn
        yarn test:no-watch
    - name: Build Test
      run: |
        yarn build
